CREATE TABLE [dbo].[ServerLogs]
(
	[Id] UNIQUEIDENTIFIER NOT NULL DEFAULT newid(),
	[UserId] UNIQUEIDENTIFIER NOT NULL,
	[Title] NVARCHAR(100) NOT NULL,
	[Action] NVARCHAR(100) NOT NULL,
	[Description] NVARCHAR(512) NOT NULL,
	[Reason] NVARCHAR(512) NULL,
	[LogDate] DATETIME NOT NULL,
	[LogType] NVARCHAR(25) NOT NULL,
	[CreatedDate] DATETIME NOT NULL,
	[LastModifiedDate] DATETIME NULL,

	PRIMARY KEY(Id),
	FOREIGN KEY(UserId) REFERENCES Users(Id)
)